import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8892);
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const page=await (await browser.newContext({viewport:{width:1366,height:820}})).newPage(); const errors=[]; page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==="error") errors.push(m.text().slice(0,200)); });
await page.goto("http://127.0.0.1:8892/?silent"); await page.waitForFunction(()=>window.__dd&&window.__heroes&&window.__weapons&&window.__doll&&window.__dd.heroModel()&&/v2/.test(window.__dd.heroModel().label),null,{timeout:120000});
const r=await page.evaluate(async()=>{ const d=window.__dd, M=window.__meta; window.__heroes.select("witch"); await new Promise(r=>setTimeout(r,3000)); M.reset(); d.resetGear(); d.start(); d.step(1/60,5); for(let i=0;i<200;i++){ d.step(1/60,1); if(window.__weapons.state().whip) break; await new Promise(r=>setTimeout(r,30)); }
  const w=d.rollItem(3,"weapon",9); w.name="Crystalheart Lash of the Hall"; M.giveItem(w); M.equip(w.id); const a=d.rollItem(2,"armor",8); a.name="Thornwoven Mail of the Hall"; M.giveItem(a); M.equip(a.id); const f=d.rollItem(4,"familiar",9); M.giveItem(f); M.equip(f.id); const c=d.rollItem(1,"charm",6); M.giveItem(c); M.equip(c.id);
  for(let i=0;i<9;i++){ M.giveItem(d.rollItem(i%5===0?3:i%3,undefined,5+i)); } M.giveGold(4200); M.addXP(900); window.__doll.open(); await new Promise(r=>setTimeout(r,900)); const bag=M.bag(); window.__doll.select(bag[0].id,"bag"); await new Promise(r=>setTimeout(r,600)); return {portrait:window.__doll.portrait(),sel:window.__doll.selected(),bag:bag.length}; });
console.log(JSON.stringify(r)); await page.screenshot({path:SP+"/parts/shots/sheet-witch.png"});
await page.evaluate(async()=>{ window.__doll.close(); window.__heroes.select("warden"); await new Promise(r=>setTimeout(r,3000)); const d=window.__dd; for(let i=0;i<200;i++){ d.step(1/60,1); const s=window.__weapons.state(); if(s.mounted&&!s.whip) break; await new Promise(r=>setTimeout(r,30)); } window.__doll.open(); await new Promise(r=>setTimeout(r,900)); });
await page.screenshot({path:SP+"/parts/shots/sheet-warden.png"}); await page.setViewportSize({width:420,height:820}); await page.waitForTimeout(500); await page.screenshot({path:SP+"/parts/shots/sheet-phone.png"});
console.log("errors",errors.length?errors.slice(0,4).join(" | "):"none"); await browser.close(); server.close();
