import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8867); const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const page=await browser.newPage({viewport:{width:960,height:600}}); const errs=[]; page.on("pageerror",e=>errs.push(String(e))); page.on("console",m=>{ if(m.type()!=="log") errs.push(m.text().slice(0,160)); });
await page.goto("http://127.0.0.1:8867/?silent"); await page.waitForFunction(()=>window.__dd&&window.__dd.heroModel()&&window.__dd.mobModel("goblin")&&window.__defglb&&(window.__defglb.list().slice||[]).filter(Boolean).length===4,null,{timeout:90000});
const info=await page.evaluate(()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.addMana(3000); d.setHero(0,10,Math.PI); const t=d.place("slice",16,12,0); d.step(1/60,30); const out={m1:{glb:!!t.mdl.userData.glb,scale:+t.mdl.scale.x.toFixed(2)}}; for(let i=0;i<3;i++){ d.setHero(t.x+1.5,t.z+1.5,0); d.step(1/60,2); d.upgrade(); } d.step(1/60,30); out.m4={lvl:t.lvl,glb:!!t.mdl.userData.glb,scale:+t.mdl.scale.x.toFixed(2),tpl:t.mdl.userData.tpl&&+t.mdl.userData.tpl.scale.toFixed(3)}; window.__t=t;
  const es=[d.spawn("goblin","N"),d.spawn("goblin","N")]; es.forEach((e,i)=>{ e.x=t.x+(i-.5)*1.2; e.z=t.z-.6; e.spd=0; e.hp=500; }); d.step(1/60,40); out.slowed=es.filter(e=>e.slowT>0).length; out.hurt=es.filter(e=>e.hp<500).length; d.setHero(t.x,t.z-5.5,0); d.setCam(0,.5,7); d.step(1/60,40); document.getElementById("hud").style.display="none"; return out; });
console.log(JSON.stringify(info)); await page.waitForTimeout(150); await page.screenshot({path:SP+"/parts/shots/ring-mk4.png"});
await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) d.kill(e); const t=window.__t; d.sellDef&&null; t.lvl=1; d.step(1/60,20); d.step(1/60,20); });
await page.waitForTimeout(150); await page.screenshot({path:SP+"/parts/shots/ring-mk1.png"});
console.log("errors:",errs.join(" | ")||"none"); await browser.close(); server.close();
