import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8858);
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const page=await browser.newPage({viewport:{width:900,height:900}}); const errs=[]; page.on("pageerror",e=>errs.push(String(e)));
await page.goto("http://127.0.0.1:8858/?silent"); await page.waitForFunction(()=>window.__dd&&window.__weapons&&window.__dd.heroModel()&&/v2/.test(window.__dd.heroModel().label),null,{timeout:60000});
const info=await page.evaluate(async()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); for(let i=0;i<80&&!window.__weapons.state().mounted;i++){ d.step(1/60,1); await new Promise(r=>setTimeout(r,50)); }
  // describe the mounted sword: meshes, material sides, local bounds, and the mount node
  const st=window.__weapons.state(); let mountNode=null; d.scene.traverse(o=>{ if(/^weaponMount_/.test(o.name)) mountNode=o; }); const sw=mountNode&&mountNode.children[0]; const meshes=[]; if(sw) sw.traverse(m=>{ if(m.isMesh&&!m.userData.isOL){ const b=new THREE.Box3().setFromBufferAttribute(m.geometry.attributes.position); meshes.push({name:m.name,side:m.material.side,verts:m.geometry.attributes.position.count,min:b.min.toArray().map(v=>+v.toFixed(2)),max:b.max.toArray().map(v=>+v.toFixed(2)),transparent:m.material.transparent,opacity:m.material.opacity,depthWrite:m.material.depthWrite}); } });
  const mp=mountNode?mountNode.getWorldPosition(new THREE.Vector3()).toArray().map(v=>+v.toFixed(2)):null; const hp=mountNode?mountNode.parent.getWorldPosition(new THREE.Vector3()).toArray().map(v=>+v.toFixed(2)):null;
  return {st,meshes,swScale:sw&&+sw.scale.x.toFixed(3),swPos:sw&&sw.position.toArray().map(v=>+v.toFixed(3)),mountWorld:mp,handWorld:hp,mountLocal:mountNode&&mountNode.position.toArray().map(v=>+v.toFixed(3)),mountQuat:mountNode&&mountNode.quaternion.toArray().map(v=>+v.toFixed(3)),hero:[+d.hero.x.toFixed(2),+d.hero.z.toFixed(2)]}; });
console.log(JSON.stringify(info,null,1));
// close-ups of the hand: camera orbits the hand at 1.6 units, three angles, for each sword type
const shots=async(tag)=>{ for(const [name,yaw] of [["front",Math.PI],["side",Math.PI/2],["back",0],["side2",-Math.PI/2]]){ await page.evaluate(({yaw})=>{ const d=window.__dd; d.setHero(0,10,0); d.setCam(yaw,.05,2.6); d.step(1/60,40); document.getElementById("hud").style.display="none"; },{yaw}); await page.waitForTimeout(120); await page.screenshot({path:SP+"/parts/shots/sword-"+tag+"-"+name+".png"}); } };
await shots("rusty");
for(const [r,nm,tag] of [[4,"Eternal Gnome Blade","holy"],[2,"Keen Broadsword","frost"],[1,"Fine Cleaver","venom"]]){ await page.evaluate(async({r,nm})=>{ const d=window.__dd; const it=d.rollItem(r,"weapon",6); it.name=nm; window.__meta.giveItem(it); window.__meta.equip(it.id); for(let i=0;i<80;i++){ d.step(1/60,1); if(window.__weapons.state().mounted&&window.__weapons.state().key.startsWith(window.__weapons.swordFor(it))) break; await new Promise(r=>setTimeout(r,40)); } },{r,nm}); await shots(tag); }
console.log("errors:",errs.join(" | ")||"none"); await browser.close(); server.close();
