import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8891);
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const page=await (await browser.newContext({viewport:{width:900,height:600}})).newPage(); const errors=[]; page.on("pageerror",e=>errors.push(String(e)));
await page.goto("http://127.0.0.1:8891/?silent"); await page.waitForFunction(()=>window.__dd&&window.__heroes&&window.__weapons&&window.__dd.heroModel()&&/v2/.test(window.__dd.heroModel().label),null,{timeout:120000});
await page.evaluate(async()=>{ window.__heroes.select("witch"); await new Promise(r=>setTimeout(r,3000)); const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.step(1/60,5); for(let i=0;i<200;i++){ d.step(1/60,1); if(window.__weapons.state().whip) break; await new Promise(r=>setTimeout(r,30)); } d.setHero(0,10,0); d.setCam(Math.PI*.5,.10,3.0); d.setHeroYaw(Math.PI*.5); d.step(1/60,90); document.getElementById("hud").style.display="none"; });
const rel=`(b=>{ const h=window.__dd.hero; const f=v=>[+(v[0]-h.x).toFixed(2),+(v[1]-h.y).toFixed(2),+(v[2]-h.z).toFixed(2)]; const st=window.__weapons.state(); return {grip:f(b.grip),tip:f(b.tip),lash:st.lash.map(f),bend:st.segBend}; })(window.__weapons.blade())`;
const frames=[["idle",0],["s4",4],["s8",8],["s12",12],["s16",16],["s24",24],["s40",40],["rest",100]];
for(const [n,f] of frames){ const r=await page.evaluate(([k,rel])=>{ const d=window.__dd; if(k===4) d.swing(); const step=k===0?1:k===40?16:k===100?60:4; d.step(1/60,step); return eval(rel); },[f,rel]); console.log(n.padEnd(5),"grip",r.grip.join(","),"tip",r.tip.join(","),"bend",r.bend.join(","),"lash",r.lash.map(p=>p.join(",")).join(" | ")); await page.waitForTimeout(120); await page.screenshot({path:SP+"/parts/shots/whip-"+n+".png"}); }
console.log("errors",errors.length?errors.join(" | "):"none"); await browser.close(); server.close();
