import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8869);
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const ctx=await browser.newContext({viewport:{width:1100,height:700}}); const page=await ctx.newPage(); const errors=[]; page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==="error"||m.type()==="warning") errors.push(m.text().slice(0,200)); });
const ready=()=>page.waitForFunction(()=>window.__dd&&window.__dd.map&&window.__campaign&&window.__dd.heroModel()&&window.__dd.mobModel("goblin")&&window.__room,null,{timeout:90000});
await page.goto("http://127.0.0.1:8869/?silent&nogate"); await ready();
const r0=await page.evaluate(()=>{ const d=window.__dd; localStorage.removeItem("ddMapsCleared"); return {map:d.map(),line:window.__campaign.line(),lanes:Object.keys(d.lanes())}; });
check("map 1 by default: The Gnome Hall, 7 waves, 4 maps, nothing cleared, start screen names it",r0.map.index===0&&r0.map.waves===7&&r0.map.total===4&&/MAP 1 OF 4/.test(r0.line)&&/GNOME HALL/.test(r0.line)&&r0.lanes.join()==="N,W,E",JSON.stringify(r0));
// a locked map falls back to map 1
await page.goto("http://127.0.0.1:8869/?silent&nogate&map=1"); await ready();
const r1=await page.evaluate(()=>window.__dd.map());
check("?map=1 while map 1 is not cleared → still map 1 (locked)",r1.index===0,JSON.stringify(r1));
// hold wave 7 → HALL HELD, map cleared, the tally offers NEXT MAP
const r2=await page.evaluate(async()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.S.wave=6; d.setHero(0,10,0); const g0=window.__meta.gold(); d.startWave(); const banner=document.getElementById("banner").textContent; const eff=d.effWave(); let n=0; for(let i=0;i<60*60;i++){ d.step(1/60,1); for(const e of d.enemies) if(!e.dead){ d.kill(e); n++; } if(d.S.phase!=="wave") break; } const phase=d.S.phase; const hud=document.getElementById("wavet").textContent; await new Promise(r=>setTimeout(r,2700)); const sum=document.getElementById("tv-sum"); const html=sum?sum.innerHTML:""; return {banner,eff,n,phase,hud,cleared:localStorage.getItem("ddMapsCleared"),tallyOpen:window.__tavern.isOpen(),held:/HALL HELD/.test(html),nextBtn:!!document.getElementById("tv-nextmap"),paid:window.__meta.gold()-g0}; });
check("wave 7 held → phase won, HALL HELD tally with NEXT MAP, map 1 marked cleared, the run paid out",r2.phase==="won"&&/WAVE 7 OF 7/.test(r2.banner)&&r2.eff===7&&r2.n>0&&/CLEARED/.test(r2.hud)&&r2.cleared==="1"&&r2.tallyOpen&&r2.held&&r2.nextBtn&&r2.paid>=25*7+150,JSON.stringify(r2));
// NEXT MAP → the throne room
await page.click("#tv-nextmap"); await page.waitForURL(/map=1/); await ready();
const r3=await page.evaluate(()=>{ const d=window.__dd; const L=d.lanes(); const paths=Object.fromEntries(Object.keys(L).map(k=>[k,d.pathLen(L[k].cx,L[k].cz)])); return {map:d.map(),lanes:Object.keys(L),from:Object.keys(L).map(k=>L[k].from),paths,crystalH:d.hgtAt(13,6),landingB:d.hgtAt(13,15),landingA:d.hgtAt(13,22),floor:d.hgtAt(13,30),flight1:+d.floorH(d.cw(20),d.cwz(25)).toFixed(2),flight2:+d.floorH(d.cw(5),d.cwz(18)).toFixed(2),flight3:+d.floorH(d.cw(13),d.cwz(11)).toFixed(2),gateW:d.hgtAt(1,22),gateE:d.hgtAt(25,15),door:window.__room.door,stations:window.__room.stations().length,line:window.__campaign.line(),wbase:d.map().wbase}; });
check("map 2 is the throne room: a 27×48 marble stair hall under a 14-high ceiling with windows; the south gate's climb is long (≥50), the west and east landing feeders (waves 3 and 5) shorter; floor 0, landings 2 and 4, throne 6, a flight between each; tavern re-homed",r3.map.index===1&&r3.map.gw===27&&r3.map.gh===48&&r3.map.wallH===14&&r3.map.windows>=6&&r3.lanes.join()==="S,W,E"&&r3.from.join()==="1,3,5"&&r3.paths.S>=50&&r3.paths.W>=24&&r3.paths.W<r3.paths.S&&r3.paths.E>=18&&r3.paths.E<r3.paths.W&&r3.crystalH===6&&r3.landingB===4&&r3.landingA===2&&r3.floor===0&&r3.flight1>0&&r3.flight1<2&&r3.flight2>2&&r3.flight2<4&&r3.flight3>4&&r3.flight3<6&&r3.gateW===2&&r3.gateE===4&&r3.stations===5&&/MAP 2 OF 4/.test(r3.line)&&r3.wbase===7,JSON.stringify(r3));
// difficulty carries on: map 2 wave 1 is the eighth wave; the feeders wait for their waves
const r4=await page.evaluate(()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.setHero(0,6,Math.PI); d.step(1/60,3); const heroY=+d.hero.y.toFixed(2); d.startWave(); const banner=document.getElementById("banner").textContent; const e=d.spawn("goblin","W"); const hp=e.hp; d.kill(e); const gates={}; for(let w=1;w<=7;w++){ d.S.phase="build"; d.S.wave=w-1; d.startWave(); gates[w]=document.getElementById("banner").textContent.replace(/.*—/,"").trim(); d.S.phase="build"; for(const x of d.enemies) d.kill(x); } d.S.wave=0; d.S.phase="build"; return {eff:d.effWave(1),banner,hp,heroY,gates}; });
check("map 2 wave 1 fights like wave 8 (goblin hp scaled, banner says WAVE 1 OF 7), hero stands on the throne platform six up; gates: south alone on waves 1–2, the west landing joins on 3, the east on 5",r4.eff===8&&/WAVE 1 OF 7/.test(r4.banner)&&r4.hp>=24&&r4.heroY>=5.9&&/^South gate$/.test(r4.gates[2])&&/South \+ West landing gates/.test(r4.gates[3])&&/West landing \+ East landing/.test(r4.gates[5]),JSON.stringify(r4));
// a goblin from the south gate climbs all three flights to the crystal; the hero climbs the first flight; a landing's face cannot be climbed straight up
const r5=await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) d.kill(e); const e=d.spawn("goblin","S"); e.spd=9; let maxY=0, reached=false; for(let i=0;i<60*40;i++){ d.step(1/60,1); maxY=Math.max(maxY,e.y); if(Math.hypot(e.x,e.z)<3.5){ reached=true; break; } if(e.dead) break; } d.kill(e);
  d.setHero(d.cw(20),d.cwz(29),Math.PI); d.hero.y=0; d.step(1/60,5); const y0=d.hero.y; d.setKeys({w:1}); for(let i=0;i<150;i++) d.step(1/60,1); d.setKeys({w:0}); const climbed=d.hero.y; d.setHero(d.cw(13),d.cwz(25),Math.PI); d.hero.y=0; d.step(1/60,5); d.setKeys({w:1}); for(let i=0;i<120;i++) d.step(1/60,1); d.setKeys({w:0}); return {maxY:+maxY.toFixed(2),reached,y0:+y0.toFixed(2),climbed:+climbed.toFixed(2),faceY:+d.hero.y.toFixed(2),faceZ:+d.hero.z.toFixed(1),landingZ:+d.cwz(23).toFixed(1)}; });
check("goblin climbs the three flights to the crystal (y reaches 6); the hero climbs the first flight to the lower landing; the landing's face stops a straight climb",r5.reached&&r5.maxY>=5.9&&r5.y0<.3&&r5.climbed>=1.9&&r5.faceY<.3&&r5.faceZ>r5.landingZ+.8,JSON.stringify(r5));
// start-screen map switch and the ◀ button
await page.goto("http://127.0.0.1:8869/?silent&nogate&map=1"); await ready();
const r6=await page.evaluate(()=>({line:window.__campaign.line(),prevOn:!document.getElementById("mapprev").disabled,nextOn:!document.getElementById("mapnext").disabled}));
check("start screen on map 2: ◀ enabled, ▶ disabled (map 3 locked)",/MAP 2 OF 4/.test(r6.line)&&r6.prevOn&&!r6.nextOn,JSON.stringify(r6));
await page.click("#mapprev"); await page.waitForURL(/map=0/); await ready();
const r7=await page.evaluate(()=>window.__dd.map());
check("◀ goes back to map 1",r7.index===0,JSON.stringify(r7));
// (the throne room's screenshots are taken by throne-test.mjs)
const realErrors=errors.filter(e=>!/Failed to load resource|favicon/i.test(e));
check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
