import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8873);
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const ctx=await browser.newContext({viewport:{width:1100,height:700}}); const page=await ctx.newPage(); const errors=[]; page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==="error"||m.type()==="warning") errors.push(m.text().slice(0,200)); });
await page.goto("http://127.0.0.1:8873/?silent"); await page.waitForFunction(()=>window.__dd&&window.__heroes&&window.__weapons&&window.__dd.heroModel()&&/v2/.test(window.__dd.heroModel().label),null,{timeout:120000});
const r0=await page.evaluate(()=>({pick:window.__heroes.pick(),line:document.getElementById("heroline").textContent,reach:window.__dd.hero.reach}));
check("default hero is the Gnome Warden with sword reach 2.4",r0.pick==="warden"&&/GNOME WARDEN/.test(r0.line)&&r0.reach===2.4,JSON.stringify(r0));
// pick the witch: model swaps live, clips present, no sword mounted, reach 3.6 and a hit lands at 3.2 units
await page.click("#heronext"); await page.waitForFunction(()=>/Witch/.test(window.__dd.heroModel().label),null,{timeout:90000});
const r1=await page.evaluate(async()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.step(1/60,5); const m=d.heroModel(); const e=d.spawn("goblin","N"); d.setHero(0,10,0); d.setCam(0,.3,6); d.step(1/60,3); e.x=0; e.z=13.2; e.spd=0; const hp0=e.hp; let ws0=window.__weapons.state(); for(let i=0;i<200&&!ws0.whip;i++){ d.step(1/60,1); ws0=window.__weapons.state(); await new Promise(r=>setTimeout(r,30)); } d.swing(); let crack=0; const hands=[], clips=[]; for(let i=0;i<40;i++){ d.step(1/60,1); e.x=0; e.z=13.2; const sr=window.__weapons.state().segBend||[]; crack=Math.max(crack,...sr.slice(1)); const hb=window.__weapons.blade(); hands.push(hb?hb.hand.map((v,k)=>+(v-[d.hero.x,d.hero.y,d.hero.z][k]).toFixed(2)):null); clips.push(d.heroModel().cur); } const hit=e.hp<hp0; d.kill(e); d.step(1/60,40); const ws=window.__weapons.state(); ws.crack=+crack.toFixed(2); ws.arm=window.__armSwing.bones(); ws.windupY=Math.max(...hands.slice(2,10).map(h=>h?h[1]:0)); ws.snapZ=Math.max(...hands.slice(10,18).map(h=>h?h[2]:0)); ws.kicked=clips.some(c=>c==='Attack'); ws.hang=ws.lash?+(ws.lash[0][1]-ws.lash[ws.lash.length-1][1]).toFixed(2):0; const rig=await window.__weapons.testWhip("whip-rope"); const crystal=window.__weapons.whipFor({name:"Crystalheart Gnome Blade",rarity:4}), bone=window.__weapons.whipFor({name:"Goblinbane Halberd",rarity:4}), rope=window.__weapons.whipFor({name:"Rusty Shortsword",rarity:0});
  return {label:m.label,clips:m.clips,reach:d.hero.reach,hit,mounted:ws.mounted,whip:ws.whip,key:ws.key,segs:ws.segs,crack:ws.crack,hang:ws.hang,mount:ws.mount,arm:ws.arm,windupY:ws.windupY,snapZ:ws.snapZ,kicked:ws.kicked,rig,crystal,bone,rope,pick:window.__heroes.pick(),saved:localStorage.getItem("ddHero"),line:document.getElementById("heroline").textContent}; });
check("witch: all six clips, whip reach 3.6 lands a hit at 3.2 units, the rope whip is mounted in her left hand (baked vine cut away), her swing is the hand-made arm strike (no kick clip: the hand winds up above her shoulder, then snaps out ahead), the 5-segment lash bends as it trails the swing and hangs down again after, and the whip set is mapped (Crystalheart → crystal, Goblinbane → bone, Rusty → rope)",/Witch/.test(r1.label)&&["idle","walk","run","attack","jump","death"].every(c=>r1.clips.includes(c))&&r1.reach===3.6&&r1.hit&&r1.mounted&&r1.whip&&/^whip-rope\|/.test(r1.key)&&r1.segs===5&&r1.crack>.5&&r1.hang>.6&&r1.mount&&r1.mount.bone==="LeftHand"&&r1.arm&&r1.arm.up==="LeftArm"&&!r1.kicked&&r1.windupY>2.0&&r1.snapZ>.6&&r1.rig.segs===5&&r1.rig.box>1.9&&r1.crystal==="whip-crystal"&&r1.bone==="whip-bone"&&r1.rope==="whip-rope"&&r1.pick==="witch"&&r1.saved==="witch"&&/FAE BATTLE WITCH/.test(r1.line),JSON.stringify(r1));
// and back to the warden: the sword returns
await page.evaluate(()=>window.__heroes.select("warden")); await page.waitForFunction(()=>/Warden/.test(window.__dd.heroModel().label),null,{timeout:90000});
const r2=await page.evaluate(async()=>{ const d=window.__dd; for(let i=0;i<150;i++){ d.step(1/60,1); const st=window.__weapons.state(); if(st.mounted&&!st.whip) break; await new Promise(r=>setTimeout(r,40)); } return {reach:d.hero.reach,sword:window.__weapons.state().mounted,whip:window.__weapons.state().whip}; });
check("warden again: reach 2.4 and the sword is back in hand",r2.reach===2.4&&r2.sword&&!r2.whip,JSON.stringify(r2));
// test shortcuts: auto-mana pulls orbs from across the hall; unlock all maps opens map 2; +1000 gold
const r3=await page.evaluate(async()=>{ const d=window.__dd; const g0=window.__meta.gold(); document.querySelector('#testline [data-t="gold"]').click(); const gold=window.__meta.gold()-g0; document.querySelector('#testline [data-t="mana"]').click(); const on=window.__autoMana; d.setHero(0,10,0); for(let i=0;i<5;i++){ const e=d.spawn("goblin","N"); e.x=0; e.z=-20; d.kill(e); } d.step(1/60,2); const orbs0=d.orbs.length; const m0=d.S.mana; for(let i=0;i<60*8&&d.orbs.length;i++) d.step(1/60,1); const got=d.S.mana-m0; document.querySelector('#testline [data-t="maps"]').click(); const line=document.getElementById("mapline").textContent, test=document.getElementById("testline").textContent, cleared=localStorage.getItem("ddMapsCleared"); const wipeBtn=document.querySelector('#testline [data-t="wipe"]'); wipeBtn.click(); const armed=/click again/.test(wipeBtn.textContent); localStorage.setItem("ddProbe","1"); window.__fresh.wipe(); const wiped=localStorage.getItem("ddProbe")===null&&localStorage.getItem("ddMapsCleared")===null; return {gold,on,orbs0,left:d.orbs.length,got,cleared,line,test,hasReload:!!document.querySelector('#testline [data-t="reload"]'),armed,wiped}; });
check("testing panel: +1000 gold, auto-mana drags orbs from 30 units away, unlock-all marks every map cleared; a fresh-reload button, and wipe saves arms on the first click and forgets every dd* key",r3.gold===1000&&r3.on&&r3.orbs0>0&&r3.left===0&&r3.got>0&&r3.cleared==="4"&&/✓/.test(r3.line)&&/unlocked ✓/.test(r3.test)&&r3.hasReload&&r3.armed&&r3.wiped,JSON.stringify(r3));
await page.evaluate(()=>window.__campaign.unlockAll()); await page.goto("http://127.0.0.1:8873/?silent&map=1"); await page.waitForFunction(()=>window.__dd&&window.__dd.map,null,{timeout:90000});
const r4=await page.evaluate(()=>window.__dd.map().index);
check("after unlock-all, ?map=1 opens the throne room",r4===1,String(r4));
// screenshot: the witch on the throne room stairs mid-whip
await page.evaluate(async()=>{ window.__heroes.select("witch"); await new Promise(r=>setTimeout(r,2500)); const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.setHero(0,30,Math.PI); d.setCam(Math.PI-.6,.22,5); const e=d.spawn("goblin","S"); d.step(1/60,2); e.x=-1; e.z=27; e.spd=0; d.step(1/60,20); d.swing(); d.step(1/60,14); document.getElementById("hud").style.display="none"; });
await page.waitForTimeout(200); await page.screenshot({path:SP+"/parts/shots/witch.png"});
const realErrors=errors.filter(e=>!/Failed to load resource|favicon/i.test(e));
check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
