import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8902);
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const ctx=await browser.newContext({viewport:{width:1000,height:640}}); const page=await ctx.newPage(); const errors=[]; page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==="error") errors.push(m.text().slice(0,200)); });
await page.goto("http://127.0.0.1:8902/?silent&nogate"); await page.waitForFunction(()=>window.__dd&&window.__defglb&&window.__defglb.list().totem&&[0,1,2,3].every(i=>window.__defglb.list().totem[i])&&window.__defglb.list().harpoon&&window.__defglb.list().harpoon[0]&&window.__dd.heroModel()&&window.__dd.mobModel("goblin"),null,{timeout:120000});
const r1=await page.evaluate(()=>{ const d=window.__dd, cfg=d.DEFS.totem, fr=d.DEFS.frost; const slot=document.getElementById("slot-totem"); const key=slot&&slot.querySelector(".k").textContent; d.start(); d.step(1/60,3); window.dispatchEvent(new KeyboardEvent("keydown",{code:"Digit6",bubbles:true})); const picked=d.ghost()&&d.ghost().ok!==undefined?true:false; const ghostKind=window.__dd.ghost()?true:false; window.dispatchEvent(new KeyboardEvent("keydown",{code:"Escape",bubbles:true}));
  const fslot=document.getElementById("slot-frost"); return {has:!!cfg,key,du:cfg.du,mana:cfg.mana,range:cfg.range,buff:cfg.buff,noChill:cfg.chill===undefined,frost:!!fr,fkey:fslot&&fslot.querySelector(".k").textContent,fchill:fr.chill,frange:fr.range,slots:document.querySelectorAll("#hotbar .slot").length,picked:ghostKind}; });
check("Rune Totem is the sixth defense (key 6: 4 DU, 70 mana, ring 7, +15% buff, no chill of its own) and the Frost Spire the seventh (key 7: ring 6, chill to 60%)",r1.has&&r1.key==="6"&&r1.slots===7&&r1.du===4&&r1.mana===70&&r1.range===7&&Math.abs(r1.buff-.15)<1e-9&&r1.noChill&&r1.frost&&r1.fkey==="7"&&Math.abs(r1.fchill-.6)<1e-9&&r1.frange===6&&r1.picked,JSON.stringify(r1));
const r2=await page.evaluate(()=>{ const d=window.__dd; if(window.__pause&&window.__pause.isOpen()) window.__pause.close(); d.S.mana=5000; for(const x of d.defs.slice()){ d.setHero(x.x,x.z+1,0); d.sell(); } d.step(1/60,5); d.setHero(8,-4,0);
  const h=d.place("harpoon",14,15,Math.PI); const t=d.place("totem",16,15,0); let far=null; for(let cz=4;cz<30&&!far;cz++) for(let cx=4;cx<30&&!far;cx++){ const c=d.cellAt(cx,cz); if((c===1||c===2)&&Math.hypot((cx-16)*2,(cz-15)*2)>10.5&&Math.hypot(cx-14,cz-15)>2){ const f=d.place("harpoon",cx,cz,0); if(f) far=f; } }
  d.step(1/60,80); const base=d.stat(far,"dmg"), cdBase=d.stat(far,"cd"); const near=d.stat(h,"dmg"), cdNear=d.stat(h,"cd"); const b1=h.buff, bFar=far.buff, r1=d.stat(t,"range"), selfBuff=t.buff;
  t.lvl=2; d.step(1/60,2); const b2=h.buff, r2=d.stat(t,"range"); const t2=d.place("totem",18,15,0); d.step(1/60,80); const stacked=h.buff; const aura=!!(t.mdl.userData.aura&&t.mdl.userData.aura.userData.ring), glb=!!t.mdl.userData.tpl;
  const e=d.spawn("goblin","N"); e.x=t.x+1.2; e.z=t.z; d.step(1/60,2); const totemChill=e.chillT||0; const f=d.place("frost",14,13,0); d.step(1/60,80); const fr=d.stat(f,"chill"); e.x=f.x+1.2; e.z=f.z; const e2=d.spawn("goblin","N"); e2.x=far.x; e2.z=far.z+1; d.step(1/60,2); const chill=e.chillT, sp=+(d.mobSpd(e)/e.spd).toFixed(2), sp2=+(d.mobSpd(e2)/e2.spd).toFixed(2); const f2=d.place("frost",12,13,0); f2.lvl=5; d.step(1/60,80); const fr5=d.stat(f2,"chill"), frRange=d.stat(f2,"range"); e.x=(f.x+f2.x)/2; e.z=f.z; d.step(1/60,2); const spBoth=+(d.mobSpd(e)/e.spd).toFixed(2); e.x=far.x; e.z=far.z+2; e.spd=0; d.step(1/60,45); const gone=e.chillT===0?true:e.chillT; const fAura=!!(f.mdl.userData.aura), fBuff=f.buff; d.kill(e); d.kill(e2);
  return {base,near,cdBase:+cdBase.toFixed(3),cdNear:+cdNear.toFixed(3),b1,bFar,r1,selfBuff,b2,r2,stacked,aura,glb,totemChill,fr,fr5,frRange,chill,sp,sp2,spBoth,gone,fAura,fBuff}; });
check("a ballista 4 units from a totem hits +15% harder and 15% faster, one far away does not, the totem itself is not buffed; Mark II → +20% and ring 8; a second totem does not stack; the Meshy model and the floor ring are on it; the totem never chills; a Frost Spire chills a goblin in its ring to 60% (Mark V to 36%, ring 9.2; the deepest cold wins where rings overlap), a far goblin is not chilled, it thaws half a second after leaving; the spire has a ring of its own and takes the totem's buff",
  Math.abs(r2.near-Math.round(r2.base*1.15*10)/10)<.11&&Math.abs(r2.cdNear-r2.cdBase/1.15)<.005&&Math.abs(r2.b1-.15)<1e-9&&r2.bFar===0&&r2.r1===7&&r2.selfBuff===0&&Math.abs(r2.b2-.2)<1e-9&&r2.r2===8&&Math.abs(r2.stacked-.2)<1e-9&&r2.aura&&r2.glb&&r2.totemChill===0&&Math.abs(r2.fr-.6)<1e-9&&Math.abs(r2.fr5-.36)<1e-9&&Math.abs(r2.frRange-9.2)<1e-9&&r2.chill>0&&r2.sp===.6&&r2.sp2===1&&r2.spBoth===.36&&r2.gone===true&&r2.fAura&&r2.fBuff>0,JSON.stringify(r2));
await page.evaluate(()=>{ const d=window.__dd; d.setHero(15,19.5,Math.PI); d.setCam(Math.PI,.35,7.5); d.step(1/60,20); document.getElementById("hud").style.display="none"; window.__freeze=true; }); await page.waitForTimeout(200); await page.screenshot({path:SP+"/parts/shots/totem.png"});
const realErrors=errors.filter(e=>!/Failed to load resource|favicon/i.test(e));
check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
