// verify-r2-test.mjs — adversarial verifier round 2 (phone + looks). SP=<scratchpad> node verify-r2-test.mjs  (port 8831)
import { chromium } from "playwright"; import http from "http"; import fs from "fs";
const SP=process.env.SP; const html=fs.readFileSync(SP+"/dungeon.html"); const server=http.createServer((q,r)=>{ r.setHeader("content-type","text/html; charset=utf-8"); r.end(html); }); await new Promise(r=>server.listen(8831,"127.0.0.1",r));
const out=[]; const log=(k,v)=>{ out.push([k,v]); console.log(k+": "+(typeof v==='string'?v:JSON.stringify(v))); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"]});
const SHOT=SP+"/parts/shots/verify-r2-"; const ready=p=>p.waitForFunction(()=>window.__dd&&window.__dd.heroModel&&window.__dd.heroModel(),null,{timeout:90000});
const LONG='Crystalheart Plate Harness of Goblin Slaying';
// ---- in-page measurement helpers ----
const measure=(sel)=>`(()=>{ const de=document.documentElement, root=document.querySelector(${JSON.stringify(sel)}); const off=[], clipX=[], clipY=[], small=[], clamp=[];
  const body=document.getElementById('tv-body'); const bodyOv=body?{sw:body.scrollWidth,cw:body.clientWidth}:null; const box=document.getElementById('tv-box'); const boxOv=box?{sw:box.scrollWidth,cw:box.clientWidth}:null;
  const nm=e=>(e.id||(typeof e.className==='string'&&e.className)||e.tagName)+':'+e.textContent.trim().replace(/\\s+/g,' ').slice(0,42);
  (root?root.querySelectorAll('*'):[]).forEach(el=>{ const r=el.getBoundingClientRect(); if(r.width>0&&(r.right>innerWidth+1||r.left<-1||r.bottom>innerHeight+1)) off.push(nm(el)+'@'+Math.round(r.left)+','+Math.round(r.top)+'-'+Math.round(r.right)+','+Math.round(r.bottom));
    const cs=getComputedStyle(el); const hidX=cs.overflowX!=='visible', hidY=cs.overflowY!=='visible';
    if(r.width>0&&el.textContent.trim()&&el.scrollWidth>el.clientWidth+1&&hidX&&cs.overflowX!=='auto'&&cs.overflowX!=='scroll') clipX.push(nm(el)+' '+el.scrollWidth+'>'+el.clientWidth);
    if(r.width>0&&el.textContent.trim()&&el.scrollHeight>el.clientHeight+1&&hidY&&cs.overflowY!=='auto'&&cs.overflowY!=='scroll'){ if(el.classList.contains('nm')) clamp.push(nm(el)); else clipY.push(nm(el)+' '+el.scrollHeight+'>'+el.clientHeight); }
    if((el.tagName==='BUTTON'||el.matches('.tv-card,.hb,[data-act],.slot'))&&r.width>0&&(r.width<44||r.height<44)) small.push(nm(el).slice(0,40)+' '+Math.round(r.width)+'x'+Math.round(r.height)); });
  return {docSW:de.scrollWidth,docSH:de.scrollHeight,iw:innerWidth,ih:innerHeight,bodyOv,boxOv,offscreen:off.slice(0,10),clipX:clipX.slice(0,10),clipY:clipY.slice(0,10),clampedNames:clamp.length,clampEx:clamp.slice(0,3),small:[...new Set(small)].slice(0,12)}; })()`;
const overlaps=(sel)=>`(()=>{ const els=[...document.querySelectorAll(${JSON.stringify(sel)})].filter(e=>e.getBoundingClientRect().width>0&&e.textContent.trim()); const res=[];
  const nm=e=>(e.id||e.className||e.tagName)+'('+e.textContent.trim().slice(0,14)+')';
  for(let i=0;i<els.length;i++) for(let j=i+1;j<els.length;j++){ if(els[i].contains(els[j])||els[j].contains(els[i])) continue; const a=els[i].getBoundingClientRect(), b=els[j].getBoundingClientRect(); const ox=Math.min(a.right,b.right)-Math.max(a.left,b.left), oy=Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top); if(ox>2&&oy>2) res.push(nm(els[i])+' x '+nm(els[j])+' '+Math.round(ox)+'x'+Math.round(oy)); }
  return [...new Set(res)].slice(0,10); })()`;
const contrast=`(()=>{ const L=c=>{ const m=c.match(/[\\d.]+/g).map(Number); const f=v=>{ v/=255; return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4); }; return .2126*f(m[0])+.7152*f(m[1])+.0722*f(m[2]); }; const ratio=(a,b)=>{ const x=L(a),y=L(b); return Math.round(((Math.max(x,y)+.05)/(Math.min(x,y)+.05))*100)/100; };
  const bg=el=>{ let e=el; while(e){ const b=getComputedStyle(e).backgroundColor, bi=getComputedStyle(e).backgroundImage; if(bi&&bi!=='none'){ const m=bi.match(/rgb\\([^)]*\\)/g); if(m) return m[m.length-1]; } if(b&&b!=='rgba(0, 0, 0, 0)'&&!/rgba\\(.*, 0\\)$/.test(b)) return b; e=e.parentElement; } return 'rgb(11,7,18)'; };
  const sels=['.tv-card .st','.tv-card .tb','.tv-card .vs','.tv-card .why','.tv-empty','.tv-sub .tv-n','.tv-sk .wh','.tv-sk .cv','.tv-detail .dm','.tv-stat span','.tv-lvl','.tv-tabs button:not(.on)','.tv-btn:disabled','#xpline','.tv-card .em','.tv-card .nm','.tv-msg','.tv-drops','#gold','.tv-card[data-from=bag] .nm'];
  return sels.map(s=>{ const el=document.querySelector(s); if(!el) return s+': n/a'; const cs=getComputedStyle(el); const r=ratio(cs.color,bg(el)); return s+': '+cs.fontSize+' '+(r<4.5?'LOW ':'')+r+(cs.opacity!=='1'?' op'+cs.opacity:''); }); })()`;
const rects=(ids)=>`(()=>{ const o={}; for(const id of ${JSON.stringify(ids)}){ const e=document.getElementById(id)||document.querySelector(id); if(!e){ o[id]=null; continue; } const b=e.getBoundingClientRect(); o[id]=[Math.round(b.left),Math.round(b.top),Math.round(b.right),Math.round(b.bottom)]; } return o; })()`;
async function seed(page){ return page.evaluate(LONG=>{ const d=window.__dd, M=window.__meta; M.reset(); M.giveGold(3000); let need=0; for(let L=1;L<8;L++) need+=M.xpToNext(L); M.addXP(need+123); M.spend('blade'); M.spend('overseer');
    const items=[]; for(let i=0;i<29;i++){ const it=d.rollItem(i%5,d.SLOTS[i%5],1+(i%15)); items.push(it); }
    items[0].name=LONG; items[1].name='Stormforged Crystal Owl of Goblin Slaying'; items[2].name='Goblinbane Warhammer of Goblin Slaying'; items[3].name='Mythic Heartstone of the Crystal Deep'; items[4].name='Crystalheart Storm Drake of Fury';
    // wear five (one per slot, middling) then fill the bag to 24
    for(let i=5;i<10;i++){ const it=items[i]; M.giveItem(it); M.equip(it.id); }
    for(const it of items){ if(M.bag().length>=24) break; if(!d.gear()[it.slot]||d.gear()[it.slot].id!==it.id) M.giveItem(it); }
    while(M.bag().length<24) M.giveItem(d.rollItem(4,'familiar',13));
    return {gold:M.gold(),level:M.level(),points:M.points(),bag:M.bag().length,rar:[0,1,2,3,4].map(r=>M.bag().filter(b=>b.rarity===r).length),stock:M.stock().length,tier:M.tierLine(),touch:document.body.classList.contains('touch'),touchBtns:[...document.querySelectorAll('#btns .hb')].map(b=>b.textContent),xpline:document.getElementById('xpline').textContent,gear:Object.fromEntries(d.SLOTS.map(s=>[s,d.gear()[s]&&d.gear()[s].name]))}; },LONG); }
const rarityCheck=`(()=>{ const M=window.__meta, d=window.__dd; const hex=h=>{ h=h.slice(1); return 'rgb('+parseInt(h.slice(0,2),16)+', '+parseInt(h.slice(2,4),16)+', '+parseInt(h.slice(4,6),16)+')'; }; const bad=[]; let n=0;
  const all=[...M.bag(),...M.stock(),...d.SLOTS.map(s=>d.gear()[s]).filter(Boolean)];
  document.querySelectorAll('#tavern .tv-card[data-id]').forEach(c=>{ const it=all.find(b=>b.id===c.dataset.id); if(!it) return; n++; const nm=c.querySelector('.nm'); if(getComputedStyle(nm).color!==hex(d.RCSS[it.rarity])) bad.push('colour '+it.name+' '+getComputedStyle(nm).color+' want '+d.RCSS[it.rarity]);
    const tb=c.querySelector('.tb'); const want='T'+d.tierOf(it.lvl); if(!tb||tb.textContent!==want||it.tier!==d.tierOf(it.lvl)) bad.push('tier '+it.name+' badge '+(tb&&tb.textContent)+' it.tier '+it.tier+' want '+want+' lvl '+it.lvl); });
  const det=document.querySelector('#tv-detail .dn2'); let detOk=null; if(det&&!document.getElementById('tv-detail').classList.contains('hide')){ const id=window.__tavern.state().sel&&window.__tavern.state().sel.id; const it=all.find(b=>b.id===id); detOk=it?(getComputedStyle(det).color===hex(d.RCSS[it.rarity])):'noitem'; }
  return {cards:n,bad:bad.slice(0,6),detailColourOk:detOk}; })()`;
async function goldSample(page,label,action){ // MutationObserver on the counter + rAF interval + polling; then a deterministic tick() replay
  await page.evaluate(()=>{ window.__gs=[]; window.__fr=[]; const el=document.getElementById('tv-goldn'); window.__gt=performance.now(); new MutationObserver(()=>window.__gs.push([Math.round(performance.now()-window.__gt),el.textContent,document.getElementById('tv-gold').className])).observe(el,{childList:true,characterData:true,subtree:true}); let last=performance.now(); const f=t=>{ window.__fr.push(Math.round(t-last)); last=t; if(window.__fr.length<40) requestAnimationFrame(f); }; requestAnimationFrame(f); });
  const g0=await page.evaluate(()=>window.__meta.gold()); await action(); const samples=[]; const t0=Date.now(); while(Date.now()-t0<1600){ samples.push(await page.evaluate(()=>document.getElementById('tv-goldn').textContent+'|'+document.getElementById('tv-gold').className)); await page.waitForTimeout(20); }
  const g1=await page.evaluate(()=>window.__meta.gold()); await page.waitForTimeout(400);
  const r=await page.evaluate(()=>({mut:window.__gs,frames:window.__fr,shown:window.__tavern.goldShown(),txt:document.getElementById('tv-goldn').textContent,cls:document.getElementById('tv-gold').className}));
  log(label,{g0,g1,distinctPolled:[...new Set(samples)].length,polled:[...new Set(samples)].slice(0,12),mutations:r.mut.length,mutSeq:r.mut.slice(0,16),rafMs:r.frames.slice(0,12),final:r.txt,cls:r.cls,shown:r.shown}); }
async function tickReplay(page,label,fn){ // drive Tavern.tick(dt) by hand at 60 Hz so the animation is judged independently of SwiftShader frame rate
  const r=await page.evaluate(fn=>{ const T=window.__tavern, seq=[]; (new Function('M','d',fn))(window.__meta,window.__dd); for(let i=0;i<50;i++){ T.tick(1/60); const t=document.getElementById('tv-goldn').textContent; if(!seq.length||seq[seq.length-1][1]!==t) seq.push([i,t,document.getElementById('tv-gold').className]); } return {steps:seq.length,seq:seq.slice(0,8),last:seq[seq.length-1],goldNow:window.__meta.gold()}; },fn);
  log(label,r); }
async function run(vp,tag){
  const phone=vp.width<500; const page=await browser.newPage({viewport:vp,deviceScaleFactor:phone?2:1,hasTouch:phone,isMobile:phone}); const errors=[]; page.on("pageerror",e=>errors.push(tag+": "+String(e))); page.on("console",m=>{ if(m.type()==="error"||m.type()==="warning") errors.push(tag+" "+m.type()+": "+m.text().slice(0,200)); });
  await page.goto("http://127.0.0.1:8831/?silent&nogate"); await ready(page); await page.waitForTimeout(300);
  const s=await seed(page); log(tag+" seed",s);
  await page.screenshot({path:SHOT+tag+"-start.png"}); log(tag+" start measure",await page.evaluate(measure('#start')));
  // ---- BAG ----
  await page.evaluate(()=>window.__dd.Meta.open()); await page.waitForTimeout(400); await page.screenshot({path:SHOT+tag+"-bag.png"});
  log(tag+" bag measure",await page.evaluate(measure('#tavern'))); log(tag+" bag overlaps",await page.evaluate(overlaps('.tv-head *, .tv-lvl *, .tv-tabs *, .tv-sub *, #tv-bag .tv-card *')));
  log(tag+" bag rarity/tier",await page.evaluate(rarityCheck));
  log(tag+" bag header",await page.evaluate(()=>({title:document.querySelector('.tv-title').textContent,titleClip:document.querySelector('.tv-title').scrollWidth>document.querySelector('.tv-title').clientWidth,gold:document.getElementById('tv-gold').textContent,lvl:[...document.querySelectorAll('.tv-lvl > *')].map(e=>e.textContent+(getComputedStyle(e).display==='none'?'(hidden)':'')),tabs:[...document.querySelectorAll('.tv-tabs button')].map(b=>b.textContent+' '+Math.round(b.getBoundingClientRect().width)+'x'+Math.round(b.getBoundingClientRect().height)+(b.scrollWidth>b.clientWidth?' CLIPPED':'')),sub:document.querySelector('#tv-bag .tv-sub').textContent,junkBtn:document.getElementById('tv-selljunk').textContent,junkCount:window.__meta.bag().filter(window.__meta.isJunk).length,vsLabels:[...document.querySelectorAll('#tv-bag .vs')].map(v=>v.textContent).slice(0,8),body:{sh:document.getElementById('tv-body').scrollHeight,ch:document.getElementById('tv-body').clientHeight}})));
  await page.evaluate(()=>{ document.getElementById('tv-body').scrollTop=99999; }); await page.waitForTimeout(150); await page.screenshot({path:SHOT+tag+"-bag-bottom.png"}); await page.evaluate(()=>{ document.getElementById('tv-body').scrollTop=0; });
  // ---- DETAIL: long-name bag item ----
  const longId=await page.evaluate(L=>window.__meta.bag().find(b=>b.name===L).id,LONG);
  await page.click('#tv-bag .tv-card[data-id="'+longId+'"]'); await page.waitForTimeout(250); await page.screenshot({path:SHOT+tag+"-detail.png"});
  log(tag+" detail measure",await page.evaluate(measure('#tv-detail'))); log(tag+" detail overlaps",await page.evaluate(overlaps('#tv-detail *'))); log(tag+" detail rarity",await page.evaluate(rarityCheck));
  log(tag+" detail content",await page.evaluate(id=>{ const M=window.__meta, d=window.__dd; const it=M.bag().find(b=>b.id===id), eq=d.gear()[it.slot]; const el=document.getElementById('tv-detail'); const c=document.querySelector('#tv-bag .tv-card[data-id="'+id+'"]').getBoundingClientRect(), r=el.getBoundingClientRect(), b=document.getElementById('tv-body').getBoundingClientRect(); const x=el.querySelector('[data-act=detclose]').getBoundingClientRect();
    return {meta:el.querySelector('.dm').textContent,deltas:[...el.querySelectorAll('.dl > div')].map(e=>e.textContent),sell:el.querySelector('[data-act=sell]').textContent,value:it.value,eqName:eq&&eq.name,eqStats:eq&&eq.stats,itStats:it.stats,cardCovered:c.bottom>r.top,cardBottom:Math.round(c.bottom),detTop:Math.round(r.top),detH:Math.round(r.height),bodyBottom:Math.round(b.bottom),xBtn:Math.round(x.width)+'x'+Math.round(x.height),btns:[...el.querySelectorAll('.db .tv-btn')].map(b=>b.textContent+' '+Math.round(b.getBoundingClientRect().width)+'x'+Math.round(b.getBoundingClientRect().height)),defendCovered:(()=>{ const f=document.getElementById('tv-defend').getBoundingClientRect(); return f.top<r.bottom&&f.bottom>r.top&&f.left<r.right&&f.right>r.left; })()}; },longId));
  // worn item detail
  const eqId=await page.evaluate(()=>window.__dd.gear().weapon.id); await page.click('#tv-bag .tv-card[data-id="'+eqId+'"][data-from=eq]'); await page.waitForTimeout(200); await page.screenshot({path:SHOT+tag+"-detail-worn.png"});
  log(tag+" worn detail",await page.evaluate(()=>({meta:document.querySelector('#tv-detail .dm').textContent,btns:[...document.querySelectorAll('#tv-detail .db .tv-btn')].map(b=>b.textContent+(b.disabled?' (disabled)':'')),bagFull:window.__meta.bagFull()})));
  // ---- GOLD COUNT-UP after a sell (real frames) ----
  const sellId=await page.evaluate(()=>window.__meta.bag().filter(b=>b.rarity>=3).sort((a,b)=>b.value-a.value)[0].id);
  await page.click('#tv-bag .tv-card[data-id="'+sellId+'"][data-from=bag]'); await page.waitForTimeout(150);
  await goldSample(page,tag+" gold count-up (sell, real frames)",async()=>{ await page.click('#tv-detail [data-act=sell]'); });
  await page.screenshot({path:SHOT+tag+"-after-sell.png"});
  log(tag+" after-sell msg",await page.evaluate(()=>({msg:document.getElementById('tv-msg').textContent,on:document.getElementById('tv-msg').classList.contains('on'),clip:document.getElementById('tv-msg').scrollWidth>document.getElementById('tv-msg').clientWidth,h:Math.round(document.getElementById('tv-msg').getBoundingClientRect().height),bag:document.querySelector('#tv-bag .tv-sub').textContent})));
  await tickReplay(page,tag+" gold count-up (tick replay, +sell)","const it=M.bag().filter(b=>b.rarity>=2)[0]; M.sell(it.id); window.__tavern.render();");
  await tickReplay(page,tag+" gold count-down (tick replay, -buy)","M.buy(0); window.__tavern.render();");
  // detail + bottom of list: is the last card reachable above the panel?
  await page.click('#tv-bag .tv-card[data-from=bag]'); await page.waitForTimeout(100); await page.evaluate(()=>{ document.getElementById('tv-body').scrollTop=99999; }); await page.waitForTimeout(150);
  log(tag+" last card vs detail",await page.evaluate(()=>{ const cs=[...document.querySelectorAll('#tv-bag .tv-card[data-from=bag]')]; const c=cs[cs.length-1].getBoundingClientRect(), d=document.getElementById('tv-detail').getBoundingClientRect(); return {lastCardBottom:Math.round(c.bottom),detailTop:Math.round(d.top),coveredPx:Math.round(c.bottom-d.top)}; }));
  await page.click('#tv-detail [data-act=detclose]'); await page.evaluate(()=>{ document.getElementById('tv-body').scrollTop=0; });
  if(phone){ const cdp=await page.context().newCDPSession(page); const st0=await page.evaluate(()=>document.getElementById('tv-body').scrollTop);
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:200,y:700}]}); for(let i=1;i<=8;i++){ await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:200,y:700-i*40}]}); await page.waitForTimeout(16); } await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]}); await page.waitForTimeout(300);
    log(tag+" touch pan scrolls tv-body",{before:st0,after:await page.evaluate(()=>document.getElementById('tv-body').scrollTop)});
    // tap a card with a real touch: does it select (no ghost click / double toggle)?
    const cr=await page.evaluate(()=>{ document.getElementById('tv-body').scrollTop=0; const c=document.querySelector('#tv-bag .tv-card[data-from=bag]'); const r=c.getBoundingClientRect(); return [r.left+r.width/2,r.top+r.height/2,c.dataset.id]; }); await page.touchscreen.tap(cr[0],cr[1]); await page.waitForTimeout(400);
    log(tag+" touch tap selects card",await page.evaluate(id=>({sel:window.__tavern.state().sel,detailShown:!document.getElementById('tv-detail').classList.contains('hide')}),cr[2])); await page.evaluate(()=>{ window.__tavern.select(null); }); }
  // ---- SHOP ----
  await page.click('#tv-tab-shop'); await page.waitForTimeout(300); await page.screenshot({path:SHOT+tag+"-shop.png"});
  log(tag+" shop measure",await page.evaluate(measure('#tavern'))); log(tag+" shop overlaps",await page.evaluate(overlaps('#tv-shop .tv-sub *, #tv-shop .tv-card *'))); log(tag+" shop rarity/tier",await page.evaluate(rarityCheck));
  log(tag+" shop cards",await page.evaluate(()=>({tierLine:document.querySelector('#tv-shop .tv-n').textContent,tierClip:document.querySelector('#tv-shop .tv-n').scrollWidth>document.querySelector('#tv-shop .tv-n').clientWidth+1,restock:document.getElementById('tv-restock').textContent,cards:[...document.querySelectorAll('#tv-shop .tv-card')].map(c=>{ const it=window.__meta.stock().find(s=>s.id===c.dataset.id); return {nm:c.querySelector('.nm').textContent,r:it.rarity,lvl:it.lvl,buy:c.querySelector('[data-act=buy]').textContent,price:it.value*3,dis:c.querySelector('[data-act=buy]').disabled,vs:(c.querySelector('.vs')||{}).textContent}; }),slots:window.__meta.stock().map(s=>s.slot),rareplus:window.__meta.stock().filter(s=>s.rarity>=2).length,minR:Math.min(...window.__meta.stock().map(s=>s.rarity))})));
  log(tag+" state before shop card click",await page.evaluate(()=>({st:window.__tavern.state(),detHidden:document.getElementById('tv-detail').classList.contains('hide'),shopOn:document.getElementById('tv-shop').classList.contains('on'),firstCard:(()=>{ const c=document.querySelector('#tv-shop .tv-card'); const r=c.getBoundingClientRect(); const e=document.elementFromPoint(r.left+r.width/2,r.top+r.height/2); return {rect:[Math.round(r.left),Math.round(r.top),Math.round(r.width),Math.round(r.height)],hit:e&&(e.id||e.className||e.tagName),hitInCard:c.contains(e)}; })()})));
  await page.click('#tv-shop .tv-card'); await page.waitForTimeout(200); await page.screenshot({path:SHOT+tag+"-shop-detail.png"});
  log(tag+" state after shop card click",await page.evaluate(()=>({st:window.__tavern.state(),detHidden:document.getElementById('tv-detail').classList.contains('hide')})));
  if(await page.evaluate(()=>document.getElementById('tv-detail').classList.contains('hide'))){ log(tag+" shop card click did not open detail — retrying via a second click",1); await page.click('#tv-shop .tv-card'); await page.waitForTimeout(200); log(tag+" state after retry",await page.evaluate(()=>({st:window.__tavern.state(),detHidden:document.getElementById('tv-detail').classList.contains('hide')}))); await page.screenshot({path:SHOT+tag+"-shop-detail.png"}); }
  log(tag+" shop detail",await page.evaluate(()=>({meta:document.querySelector('#tv-detail .dm').textContent,price:[...document.querySelectorAll('#tv-detail .dm')].map(e=>e.textContent),btns:[...document.querySelectorAll('#tv-detail .db .tv-btn')].map(b=>b.textContent+(b.disabled?' (disabled)':''))})));
  await page.evaluate(()=>{ window.__tavern.select(null); });
  // poor: no gold → reason line under every Buy
  await page.evaluate(()=>{ const M=window.__meta; M.addGold(-M.gold(),'test'); window.__tavern.render(); }); await page.waitForTimeout(900); await page.screenshot({path:SHOT+tag+"-shop-poor.png"});
  log(tag+" shop poor",await page.evaluate(measure('#tv-shop'))); log(tag+" shop poor why",await page.evaluate(()=>[...document.querySelectorAll('#tv-shop .why')].map(w=>w.textContent+' @'+getComputedStyle(w).fontSize+' '+(w.scrollWidth>w.clientWidth?'CLIP':'ok'))));
  // bag full (24) with gold → 'Bag is full' reason
  await page.evaluate(()=>{ const M=window.__meta, d=window.__dd; M.giveGold(3000); while(M.bag().length<24) M.giveItem(d.rollItem(0,'charm',2)); window.__tavern.render(); }); await page.waitForTimeout(900);
  log(tag+" shop bag-full why",await page.evaluate(()=>({bag:window.__meta.bag().length,why:[...new Set([...document.querySelectorAll('#tv-shop .why')].map(w=>w.textContent))],dis:[...document.querySelectorAll('#tv-shop [data-act=buy]')].every(b=>b.disabled)})));
  await page.screenshot({path:SHOT+tag+"-shop-bagfull.png"});
  // sold out state
  await page.evaluate(()=>{ const M=window.__meta; M.giveGold(50000); while(M.bag().length>6) M.sell(M.bag()[0].id); while(M.stock().length) M.buy(0); window.__tavern.render(); }); await page.waitForTimeout(900); await page.screenshot({path:SHOT+tag+"-shop-empty.png"});
  log(tag+" shop empty state",await page.evaluate(()=>({empty:(document.querySelector('#tv-shop .tv-empty')||{}).textContent,gold:document.getElementById('tv-goldn').textContent,restockDis:document.getElementById('tv-restock').disabled})));
  await page.evaluate(()=>{ window.__meta.restock(); window.__tavern.render(); }); await page.waitForTimeout(300);
  // ---- SKILLS ----
  await page.click('#tv-tab-skills'); await page.waitForTimeout(300); await page.screenshot({path:SHOT+tag+"-skills.png"});
  log(tag+" skills measure",await page.evaluate(measure('#tavern'))); log(tag+" skills overlaps",await page.evaluate(overlaps('#tv-skills .tv-sub *, #tv-skills .tv-sk *')));
  log(tag+" skills rows",await page.evaluate(()=>({sub:document.querySelector('#tv-skills .tv-sub').textContent,rows:[...document.querySelectorAll('#tv-skills .tv-sk')].map(r=>({nm:r.querySelector('.nm').textContent,wh:r.querySelector('.wh').textContent,cv:r.querySelector('.cv').textContent,on:r.querySelectorAll('.tv-pips i.on').length,dis:r.querySelector('[data-act=spend]').disabled,h:Math.round(r.getBoundingClientRect().height),pipsW:Math.round(r.querySelector('.tv-pips').getBoundingClientRect().width)}))})));
  await page.click('#tv-sk-vigor [data-act=spend]'); await page.waitForTimeout(200); log(tag+" spend click",await page.evaluate(()=>({msg:document.getElementById('tv-msg').textContent,pts:document.getElementById('tv-pts').textContent,vigor:document.querySelector('#tv-sk-vigor .cv').textContent,on:document.querySelectorAll('#tv-sk-vigor .tv-pips i.on').length,hudXp:document.getElementById('xpline').textContent})));
  await page.evaluate(()=>{ const M=window.__meta; M.addXP(200000); for(let i=0;i<10;i++) M.spend('blade'); window.__tavern.render(); }); await page.waitForTimeout(300); await page.screenshot({path:SHOT+tag+"-skills-max.png"});
  log(tag+" skills maxed",await page.evaluate(()=>({cv:document.querySelector('#tv-sk-blade .cv').textContent,dis:document.querySelector('#tv-sk-blade [data-act=spend]').disabled,head:[...document.querySelectorAll('.tv-lvl > *')].map(e=>e.textContent),xpline:document.getElementById('xpline').textContent,hudGold:document.getElementById('gold').textContent,lvlW:Math.round(document.querySelector('.tv-lvl').scrollWidth)+'/'+Math.round(document.querySelector('.tv-lvl').clientWidth)})));
  log(tag+" contrast (skills tab)",await page.evaluate(contrast));
  // ---- EMPTY BAG ----
  await page.evaluate(()=>{ const M=window.__meta, d=window.__dd; while(M.bag().length) M.sell(M.bag()[0].id); for(const s of d.SLOTS) if(d.gear()[s]){ M.unequip(s); M.sell(M.bag()[0].id); } window.__tavern.tab('bag'); window.__tavern.render(); }); await page.waitForTimeout(900); await page.screenshot({path:SHOT+tag+"-bag-empty.png"});
  log(tag+" empty bag",await page.evaluate(()=>({empty:(document.querySelector('#tv-bag .tv-empty')||{}).textContent,ems:[...document.querySelectorAll('#tv-bag .em')].map(e=>e.textContent),junk:document.getElementById('tv-selljunk').textContent,junkDis:document.getElementById('tv-selljunk').disabled,sub:document.querySelector('#tv-bag .tv-sub').textContent})));
  await page.click('#tv-bag .tv-card[data-from=eq]'); await page.waitForTimeout(100); log(tag+" tap empty slot msg",await page.evaluate(()=>document.getElementById('tv-msg').textContent));
  // ---- CLOSE, PLAY, HUD ----
  await page.evaluate(()=>{ window.__tavern.close(); }); await seed(page);
  await page.evaluate(()=>{ const d=window.__dd; d.start(); d.step(1/60,5); }); await page.waitForTimeout(300); await page.screenshot({path:SHOT+tag+"-hud.png"});
  log(tag+" hud rects",await page.evaluate(rects(['.bars','.res','gear','xpline','topC','wavebtn','bagbtn','sndbtn','hotbar','btns','joy'])));
  log(tag+" hud",await page.evaluate(()=>({resSW:document.querySelector('.res').scrollWidth,resCW:document.querySelector('.res').clientWidth,resTxt:document.querySelector('.res').textContent.replace(/\s+/g,' '),xp:document.getElementById('xpline').textContent,gold:document.getElementById('gold').textContent,gearLines:[...document.querySelectorAll('#gear .gr')].map(g=>g.textContent.slice(0,50)+(g.scrollWidth>g.clientWidth?' (ellipsis)':'')),bagbtn:(()=>{ const r=document.getElementById('bagbtn').getBoundingClientRect(); return Math.round(r.width)+'x'+Math.round(r.height); })(),hb:[...document.querySelectorAll('#btns .hb')].map(b=>{ const r=b.getBoundingClientRect(); return b.textContent+' '+Math.round(r.top); })})));
  log(tag+" hud overlaps",await page.evaluate(overlaps('#hud .bars *, #topC *, #bagbtn, #sndbtn, #wavebtn, #btns .hb, #hotbar .slot, #xpline, #gear .gr')));
  // bagged toast with a long name; wave held → HUD gold
  const held=await page.evaluate(L=>{ const d=window.__dd; const it=d.rollItem(4,'armor',9); it.name=L; d.Meta.onPickup(it,{x:d.hero.x,y:0,z:d.hero.z}); d.step(1/60,1); const t=document.getElementById('toast'); const r=t.getBoundingClientRect(); const g0=document.getElementById('gold').textContent; d.Meta.onWaveHeld(3); d.step(1/60,1); return {toast:t.textContent,toastW:Math.round(r.width),toastRight:Math.round(r.right),toastLeft:Math.round(r.left),toastClip:t.scrollWidth>t.clientWidth,g0,g1:document.getElementById('gold').textContent,xp:document.getElementById('xpline').textContent}; },LONG); log(tag+" hud toast + wave gold",held);
  await page.waitForTimeout(150); await page.screenshot({path:SHOT+tag+"-hud-toast.png"});
  // open the tavern from the HUD (touch 🎒 / #bagbtn) during play
  if(phone){ const bb=await page.evaluate(()=>{ const b=[...document.querySelectorAll('#btns .hb')].find(b=>b.textContent==='🎒'); if(!b) return null; const r=b.getBoundingClientRect(); return [r.left+r.width/2,r.top+r.height/2,Math.round(r.width),Math.round(r.height)]; });
    log(tag+" touch 🎒 present",bb); if(bb){ await page.touchscreen.tap(bb[0],bb[1]); await page.waitForTimeout(300); log(tag+" touch 🎒 opens tavern",await page.evaluate(()=>({open:window.__dd.Meta.isOpen(),phase:window.__dd.S.phase,lbl:document.getElementById('tv-defend').textContent,goldHdr:document.getElementById('tv-gold').textContent}))); await page.screenshot({path:SHOT+tag+"-tavern-inplay.png"}); await page.evaluate(()=>window.__tavern.close()); } }
  else { await page.click('#bagbtn'); await page.waitForTimeout(200); log(tag+" bagbtn opens",await page.evaluate(()=>({open:window.__dd.Meta.isOpen(),lbl:document.getElementById('tv-defend').textContent}))); await page.keyboard.press('KeyB'); await page.waitForTimeout(100); log(tag+" B closes",await page.evaluate(()=>window.__dd.Meta.isOpen())); }
  // ---- RUN END → SUMMARY (wave 7, 9 legendary drops incl. long names) ----
  const sum=await page.evaluate(L=>{ const d=window.__dd; d.S.wave=7; d.S.kills=123; for(let i=0;i<9;i++){ const it=d.rollItem(4,d.SLOTS[i%5],7); if(i===0) it.name=L; if(i===1) it.name='Stormforged Crystal Owl of Goblin Slaying'; d.Meta.onPickup(it,null); } d.S.phase='dead'; d.Meta.onKill({kind:'ogre'}); const r=d.Meta.onRunEnd(7); d.step(1/60,2); return {r,h1:document.querySelector('#tv-sum h1').textContent,h2:document.querySelector('#tv-sum h2').textContent,stats:[...document.querySelectorAll('.tv-stat')].map(s=>s.textContent),drops:document.querySelector('.tv-drops').textContent.slice(0,160),sumData:d.Meta.summary()}; },LONG);
  await page.waitForTimeout(400); await page.screenshot({path:SHOT+tag+"-summary.png"}); log(tag+" summary",sum);
  log(tag+" summary measure",await page.evaluate(measure('#tv-sum'))); log(tag+" summary overlaps",await page.evaluate(overlaps('#tv-sum *')));
  log(tag+" summary layout",await page.evaluate(()=>{ const s=document.getElementById('tv-sum'); const h1=s.querySelector('h1').getBoundingClientRect(), b=document.getElementById('tv-totavern').getBoundingClientRect(), a=document.getElementById('tv-again').getBoundingClientRect(); const dropCols=[...s.querySelectorAll('.tv-drops b')].map(x=>getComputedStyle(x).color); return {sh:s.scrollHeight,ch:s.clientHeight,scrollTop:s.scrollTop,h1Top:Math.round(h1.top),h1Visible:h1.top>=0,btnBottom:Math.round(Math.max(b.bottom,a.bottom)),btnsVisible:Math.max(b.bottom,a.bottom)<=innerHeight,btnH:Math.round(b.height)+'/'+Math.round(a.height),dropColours:[...new Set(dropCols)],statFont:getComputedStyle(s.querySelector('.tv-stat b')).fontSize}; }));
  await goldSample(page,tag+" totavern count-up (real frames)",async()=>{ await page.click('#tv-totavern'); });
  log(tag+" after totavern",await page.evaluate(()=>({tab:window.__tavern.state().tab,lbl:document.getElementById('tv-defend').textContent,best:document.getElementById('tv-best').textContent,bestHidden:getComputedStyle(document.getElementById('tv-best')).display==='none',phase:window.__dd.S.phase,deadHidden:document.getElementById('dead').classList.contains('hide')})));
  await page.screenshot({path:SHOT+tag+"-tavern-after-run.png"});
  await page.click('#tv-tab-shop'); await page.waitForTimeout(300); await page.screenshot({path:SHOT+tag+"-shop-t4.png"});
  log(tag+" shop after run",await page.evaluate(()=>({tier:window.__meta.tierLine(),tierClip:document.querySelector('#tv-shop .tv-n').scrollWidth>document.querySelector('#tv-shop .tv-n').clientWidth+1,tierW:document.querySelector('#tv-shop .tv-n').scrollWidth+'/'+document.querySelector('#tv-shop .tv-n').clientWidth,cards:[...document.querySelectorAll('#tv-shop .tv-card')].map(c=>c.querySelector('.tb').textContent+' lvl'+window.__meta.stock().find(s=>s.id===c.dataset.id).lvl+' '+c.querySelector('[data-act=buy]').textContent)})));
  log(tag+" shop t4 rarity/tier",await page.evaluate(rarityCheck)); log(tag+" shop t4 measure",await page.evaluate(measure('#tavern')));
  // Escape from the after-run tavern → old #dead screen shows?
  await page.keyboard.press('Escape'); await page.waitForTimeout(150); log(tag+" esc after run",await page.evaluate(()=>({open:window.__dd.Meta.isOpen(),dead:!document.getElementById('dead').classList.contains('hide'),deadTxt:document.querySelector('#dead h2').textContent}))); await page.screenshot({path:SHOT+tag+"-after-esc.png"});
  log(tag+" errors",errors);
  await page.close(); }
// ---- landscape phone: the HUD with six touch buttons + the tavern ----
async function landscape(){ const tag='land'; const page=await browser.newPage({viewport:{width:844,height:390},deviceScaleFactor:2,hasTouch:true,isMobile:true}); const errors=[]; page.on("pageerror",e=>errors.push(String(e)));
  await page.goto("http://127.0.0.1:8831/?silent&nogate"); await ready(page); await page.waitForTimeout(300); await seed(page);
  await page.evaluate(()=>{ const d=window.__dd; d.start(); d.step(1/60,5); }); await page.waitForTimeout(300); await page.screenshot({path:SHOT+tag+"-hud.png"});
  log(tag+" hud rects",await page.evaluate(rects(['.bars','xpline','topC','wavebtn','bagbtn','sndbtn','hotbar','btns','joy'])));
  log(tag+" hud overlaps",await page.evaluate(overlaps('#hud .bars *, #topC *, #bagbtn, #sndbtn, #wavebtn, #btns .hb, #hotbar .slot, #xpline, #gear .gr')));
  log(tag+" hb offscreen",await page.evaluate(()=>[...document.querySelectorAll('#btns .hb')].map(b=>{ const r=b.getBoundingClientRect(); return b.textContent+'@'+Math.round(r.top)+(r.top<0?' OFFSCREEN':''); })));
  await page.evaluate(()=>window.__dd.Meta.open()); await page.waitForTimeout(400); await page.screenshot({path:SHOT+tag+"-bag.png"});
  log(tag+" bag measure",await page.evaluate(measure('#tavern'))); log(tag+" bag body",await page.evaluate(()=>{ const b=document.getElementById('tv-body').getBoundingClientRect(); return {bodyH:Math.round(b.height),sh:document.getElementById('tv-body').scrollHeight}; }));
  await page.click('#tv-bag .tv-card[data-from=bag]'); await page.waitForTimeout(250); await page.screenshot({path:SHOT+tag+"-detail.png"});
  log(tag+" detail",await page.evaluate(()=>{ const d=document.getElementById('tv-detail').getBoundingClientRect(), b=document.getElementById('tv-body').getBoundingClientRect(); return {detH:Math.round(d.height),detTop:Math.round(d.top),bodyTop:Math.round(b.top),bodyBottom:Math.round(b.bottom),listVisiblePx:Math.round(d.top-b.top),sh:document.getElementById('tv-detail').scrollHeight,ch:document.getElementById('tv-detail').clientHeight}; }));
  log(tag+" errors",errors); await page.close(); }
const W=process.env.WHICH||'phone,desktop,land';
if(W.includes('phone')) await run({width:390,height:844},"phone");
if(W.includes('desktop')) await run({width:1280,height:800},"desktop");
if(W.includes('land')) await landscape();
await browser.close(); server.close(); fs.writeFileSync(SP+"/parts/shots/verify-r2-log-"+W.replace(/,/g,"-")+".json",JSON.stringify(out,null,1)); console.log("done");
