import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8893);
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const ctx=await browser.newContext({viewport:{width:1100,height:700}}); const page=await ctx.newPage(); const errors=[]; page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==="error") errors.push(m.text().slice(0,200)); });
await page.goto("http://127.0.0.1:8893/?silent&nogate"); await page.waitForFunction(()=>window.__dd&&window.__void&&window.__sets&&window.__weapons&&window.__doll&&window.__dd.heroModel()&&/v2/.test(window.__dd.heroModel().label)&&window.__dd.mobModel("goblin"),null,{timeout:120000});
// 1. the set exists; the drop rule: nothing before wave 4, 5% of rare+ at wave 4, 15% cap; commons never
const r1=await page.evaluate(()=>{ const d=window.__dd, V=window.__void; d.start(); const roll=(w,n,minR)=>{ d.S.wave=w; let k=0; for(let i=0;i<n;i++){ const it=d.rollItem(minR,"weapon",w); if(V.isVoid(it)) k++; } return k/n; };
  return {has:!!window.__sets.SETS["of the Void"],names:window.__sets.names.includes("of the Void"),c3:V.chance.call(null),w3:(d.S.wave=3,V.chance()),w4:(d.S.wave=4,V.chance()),w14:(d.S.wave=14,V.chance()),w20:(d.S.wave=20,V.chance()),rateW6:roll(6,3000,2),rateCommon:roll(6,1500,0)*0+(()=>{ let k=0; for(let i=0;i<1500;i++){ const it=d.rollItem(0,"armor",6); it.rarity<2&&V.isVoid(it)&&k++; } return k; })()}; });
check("of the Void is a set; no Void drops before wave 4, 5% of Rare+ at wave 4, 15% cap from wave 14; ~7% of Rare+ rolls at wave 6; never on Common/Uncommon",r1.has&&r1.names&&r1.w3===0&&Math.abs(r1.w4-.05)<1e-9&&Math.abs(r1.w14-.15)<1e-9&&Math.abs(r1.w20-.15)<1e-9&&r1.rateW6>.04&&r1.rateW6<.11&&r1.rateCommon===0,JSON.stringify(r1));
// 2. making a piece Void: the old suffix goes, value ×3; it drops with its own sound, a column and a shout, glows violet on the floor
const r2=await page.evaluate(()=>{ const d=window.__dd, V=window.__void; d.S.wave=6; const it=d.rollItem(3,"amulet",8); it.name="Stormforged Halberd of the Deep"; it.value=100; V.make(it); const sfx=[]; const o1=d.Meta&&null; const S_=window.__dd; const orig=window.__sfxSpy; 
  let played=0; const sfxObj=(()=>{ try{ return SFX; }catch(e){ return null; } })(); return {name:it.name,value:it.value,setOf:window.__sets.setOf(it)}; });
const r2b=await page.evaluate(()=>{ const d=window.__dd, V=window.__void; const it=d.rollItem(3,"charm",8); V.make(it); let played=0; const sp=window.__spy=(k)=>{ played++; }; d.setHero(0,10,0); const fx0=V.fx(); const before=document.getElementById("hud").innerHTML; const l=d.dropLoot(it,2,10); d.step(1/60,2); const fxN=V.fx(); let violet=false; l.mesh.traverse(m=>{ if(m.isMesh&&m.material&&m.material.color&&m.material.color.getHex()===0x8a3dff) violet=true; }); d.step(1/60,200); return {fx0,fxN,violet,gone:V.fx()}; });
check("a Void piece: suffix swapped, worth ×3 (Halberd of the Deep → of the Void, 100 → 300); its drop raises a violet column that fades in 3 s and recolours the piece on the floor",r2.name==="Stormforged Halberd of the Void"&&r2.value===300&&r2.setOf==="of the Void"&&r2b.fxN===r2b.fx0+1&&r2b.violet&&r2b.gone===0,JSON.stringify({r2,r2b}));
// 3. three pieces: +15% hero damage, +20% familiar damage; five: the rift — a hit slows the target and hurts everyone within 3 units
const r3=await page.evaluate(async()=>{ const d=window.__dd, M=window.__meta, V=window.__void; M.reset(); d.resetGear(); const mk=(slot)=>{ const it=d.rollItem(2,slot,6); it.rarity=2; V.make(it); M.giveItem(it); M.equip(it.id); return it; }; const dmg0=d.heroDmg(); const fam0=window.__familiar&&window.__familiar.dmg?window.__familiar.dmg():null;
  mk("weapon"); mk("armor"); mk("charm"); const dmg3=d.heroDmg(), lvl3=V.lvl(), mult3=+d.heroMult("dmg").toFixed(3); mk("amulet"); mk("familiar"); const lvl5=V.lvl(); const sheet=(window.__doll.open(),await new Promise(r=>setTimeout(r,300)),window.__doll.html()); window.__doll.close();
  d.setHero(0,10,0); d.setCam(0,.3,6); d.step(1/60,3); const X=[0,1.5,-1.2,6], Z=[12,12.5,13,12]; const es=[]; for(let i=0;i<4;i++){ const e=d.spawn("goblin","N"); e.spd=0; e.hp=e.max=200; es.push(e); } const put=()=>es.forEach((e,i)=>{ e.x=X[i]; e.z=Z[i]; e.spd=0; }); put(); const hp=es.map(e=>e.hp); d.step(1/60,2); put();   /* the hit cone looks down +z; the pet also shoots, so the rift is read off the slow and a lower bound on damage */
  d.swing(); for(let i=0;i<40;i++){ d.step(1/60,1); put(); } const lost=es.map((e,i)=>+(hp[i]-e.hp).toFixed(1)), slow=es.map(e=>+(e.slowT||0).toFixed(1)); es.forEach(e=>d.kill(e)); 
  return {dmg0,dmg3,mult3,lvl3,lvl5,lost,slow,hasSet:/of the Void 5\/5/.test(sheet),weapon:window.__weapons.state()}; });
check("three Void pieces: ×1.15 hero damage; five: set level 5, the sheet says of the Void 5/5, a hit on the front goblin rifts the two beside it (40% of the blow) and slows all three for 2 s, the far one untouched; the worn Void weapon mounts the runed model, darkened and burning violet",r3.lvl3===3&&r3.lvl5===5&&Math.abs(r3.mult3-1.15)<1e-6&&r3.dmg3>r3.dmg0&&r3.lost[0]>=r3.dmg3&&r3.lost[1]>=Math.round(r3.dmg3*.4*10)/10-.1&&r3.lost[2]>=Math.round(r3.dmg3*.4*10)/10-.1&&r3.slow[0]>1.2&&r3.slow[1]>1.2&&r3.slow[2]>1.2&&r3.slow[3]===0&&r3.hasSet&&r3.weapon.void&&/^holy\|/.test(r3.weapon.key),JSON.stringify(r3));
const r4=await page.evaluate(async()=>{ const d=window.__dd, M=window.__meta, V=window.__void, P=window.__packs; M.reset(); d.resetGear(); const mk=(slot)=>{ const it=d.rollItem(2,slot,6); it.rarity=2; V.make(it); M.giveItem(it); M.equip(it.id); return it; }; mk("weapon"); mk("armor"); mk("charm"); mk("amulet"); d.step(1/60,2); const four=P.aura(); mk("familiar"); d.step(1/60,2); const five=P.aura(); const glow=[]; d.scene.traverse(o=>{ if(o.userData.setGlow) glow.push(o); }); const skinnedGlow=glow.filter(g=>g.isSkinnedMesh).length; M.unequip("charm"); d.step(1/60,2); const after=P.aura(); const left=[]; d.scene.traverse(o=>{ if(o.userData.setGlow) left.push(o); });
  P.get("of the Void").art.sword="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="; const bagSword=d.rollItem(2,"weapon",6); bagSword.rarity=2; V.make(bagSword); M.giveItem(bagSword); const plain=d.rollItem(1,"armor",6); plain.name="Plain Jerkin"; M.giveItem(plain); window.__doll.open(); await new Promise(r=>setTimeout(r,300)); const html=window.__doll.html(); window.__doll.close(); const slotImg=/dl-slot dl-pane weapon[\s\S]*?<img class="ia" src="data:image\/png/.test(html); const gridImg=(html.match(/inv-c has[^>]*>[\s\S]*?<img class="ia"/g)||[]).length>=1; const emojiKept=new RegExp('data-id="'+plain.id+'"[^>]*><span>🛡</span>').test(html); window.__tavern.open(); await new Promise(r=>setTimeout(r,300)); const tav=document.getElementById("tavern").innerHTML; window.__tavern.close(); const tavImg=/tv-card[\s\S]*?<span class="ic"><img class="ia" src="data:image\/png/.test(tav); return {four,five,skinnedGlow,after,left:left.length,slotImg,gridImg,emojiKept,tavImg}; });
check("four Void pieces: no aura; five: a violet shell on the hero's skinned meshes, attached, gone again when a piece comes off; card art: the Void sword's picture shows in the sheet's weapon slot, the inventory grid and a tavern card, a piece without art keeps its emoji",!r4.four.on&&r4.five.on&&r4.five.col===0x8a3dff&&r4.five.attached===r4.five.meshes&&r4.skinnedGlow>0&&!r4.after.on&&r4.left===0&&r4.slotImg&&r4.gridImg&&r4.emojiKept&&r4.tavImg,JSON.stringify(r4));
const realErrors=errors.filter(e=>!/Failed to load resource|favicon/i.test(e));
check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
